<a href="https://colab.research.google.com/github/AnHaiTrinh/handson-ml/blob/main/CustomModel%26TF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

import sklearn

import tensorflow as tf
from tensorflow import keras

%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

In [ ]:
tf.constant([[1., 2., 3.], [4., 5., 6.]])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [ ]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [ ]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])

In [ ]:
t[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [ ]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [ ]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [ ]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [ ]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [ ]:
K = keras.backend
K.square(K.transpose(t)) + 10

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[11., 26.],
       [14., 35.],
       [19., 46.]], dtype=float32)>

In [ ]:
a = np.array([2., 4., 5.])

In [ ]:
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [ ]:
t.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [ ]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

In [ ]:
np.square(t)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

In [ ]:
t2 = tf.constant(40, dtype=tf.float64)
tf.constant(2.) + tf.cast(t2, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

In [ ]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [ ]:
v.assign(v*2)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [ ]:
v[0, 1].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [ ]:
v[:, 2].assign([0., 1.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  0.],
       [ 8., 10.,  1.]], dtype=float32)>

In [ ]:
v.scatter_nd_update(indices=[[0, 0],[1, 1]], updates=[6., 9.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 6., 42.,  0.],
       [ 8.,  9.,  1.]], dtype=float32)>

In [ ]:
tf.constant(b"hello world")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello world'>

In [ ]:
u = tf.constant([ord(c) for c in "café"])

In [ ]:
b = tf.strings.unicode_encode(u, "UTF-8")
tf.strings.length(b, unit="UTF8_CHAR")

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
tf.strings.unicode_decode(b, "UTF-8")

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 99,  97, 102, 233], dtype=int32)>

In [ ]:
array = tf.TensorArray(dtype=tf.float32, size=3)
array = array.write(0, tf.constant([1., 2.]))
array = array.write(1, tf.constant([3., 10.]))
array = array.write(2, tf.constant([5., 7.]))

In [ ]:
array.read(1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 3., 10.], dtype=float32)>

In [ ]:
array.stack()

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [0., 0.],
       [5., 7.]], dtype=float32)>

In [ ]:
mean, variance = tf.nn.moments(array.stack(), axes=0)

In [ ]:
mean

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [ ]:
variance

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.6666665, 8.666667 ], dtype=float32)>

In [ ]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

housing = fetch_california_housing()
X, y = housing.data, housing.target.reshape(-1, 1)
X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.2)
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full, test_size=0.2)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)
X_test_scaled = scaler.transform(X_test)

In [ ]:
def huber_fn(y_true, y_pred):
  error = tf.abs(y_true - y_pred)
  small_error = error < 1
  squared_loss = tf.square(error) / 2
  linear_loss = error - 0.5
  return tf.where(small_error, squared_loss, linear_loss)

In [ ]:
model = keras.models.Sequential([
                                 keras.layers.Dense(30, activation='selu', kernel_initializer="lecun_normal", input_shape=X_train.shape[1:]),
                                 keras.layers.Dense(1)
])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 30)                270       
                                                                 
 dense_1 (Dense)             (None, 1)                 31        
                                                                 
Total params: 301
Trainable params: 301
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss=huber_fn, optimizer="nadam", metrics=['mae'])
history = model.fit(X_train_scaled, y_train, epochs=10, validation_data=(X_valid_scaled, y_valid))

Epoch 1/10
413/413 [==============================] - 4s 5ms/step - loss: 0.5169 - mae: 0.8641 - val_loss: 0.2163 - val_mae: 0.5190
Epoch 2/10
413/413 [==============================] - 2s 5ms/step - loss: 0.2099 - mae: 0.5076 - val_loss: 0.1975 - val_mae: 0.4932
Epoch 3/10
413/413 [==============================] - 2s 6ms/step - loss: 0.1989 - mae: 0.4903 - val_loss: 0.1908 - val_mae: 0.4814
Epoch 4/10
413/413 [==============================] - 2s 4ms/step - loss: 0.1921 - mae: 0.4795 - val_loss: 0.1873 - val_mae: 0.4757
Epoch 5/10
413/413 [==============================] - 2s 4ms/step - loss: 0.1882 - mae: 0.4730 - val_loss: 0.1774 - val_mae: 0.4576
Epoch 6/10
413/413 [==============================] - 2s 4ms/step - loss: 0.1845 - mae: 0.4672 - val_loss: 0.1765 - val_mae: 0.4601
Epoch 7/10
413/413 [==============================] - 2s 4ms/step - loss: 0.1813 - mae: 0.4627 - val_loss: 0.1746 - val_mae: 0.4541
Epoch 8/10
413/413 [==============================] - 2s 4ms/step - loss: 0.

In [ ]:
model.save("my_model_with_custom_loss.h5")

In [ ]:
model = keras.models.load_model("my_model_with_custom_loss.h5",
                                custom_objects={"huber_fn": huber_fn})

In [ ]:
model.fit(X_train_scaled, y_train, epochs=5, validation_data=(X_valid_scaled, y_valid))

Epoch 1/5
413/413 [==============================] - 3s 5ms/step - loss: 0.1736 - mae: 0.4493 - val_loss: 0.1694 - val_mae: 0.4429
Epoch 2/5
413/413 [==============================] - 2s 4ms/step - loss: 0.1721 - mae: 0.4464 - val_loss: 0.1693 - val_mae: 0.4443
Epoch 3/5
413/413 [==============================] - 2s 4ms/step - loss: 0.1711 - mae: 0.4443 - val_loss: 0.1658 - val_mae: 0.4388
Epoch 4/5
413/413 [==============================] - 2s 4ms/step - loss: 0.1695 - mae: 0.4422 - val_loss: 0.1692 - val_mae: 0.4417
Epoch 5/5
413/413 [==============================] - 1s 3ms/step - loss: 0.1690 - mae: 0.4408 - val_loss: 0.1635 - val_mae: 0.4353


In [ ]:
def create_huber(threshold=1.0):
  def huber_fn(y_true, y_pred):
    error = tf.abs(y_true - y_pred)
    small_error = error < threshold
    squared_loss = tf.square(error) / 2
    linear_loss = threshold * (error - threshold / 2)
    return tf.where(small_error, squared_loss, linear_loss)
  return huber_fn

In [ ]:
model.compile(loss=create_huber(2.0), optimizer="nadam", metrics=['mae'])
history = model.fit(X_train_scaled, y_train, epochs=10, validation_data=(X_valid_scaled, y_valid))

Epoch 1/10
413/413 [==============================] - 3s 5ms/step - loss: 0.1878 - mae: 0.4419 - val_loss: 0.1836 - val_mae: 0.4425
Epoch 2/10
413/413 [==============================] - 2s 4ms/step - loss: 0.1873 - mae: 0.4407 - val_loss: 0.1823 - val_mae: 0.4357
Epoch 3/10
413/413 [==============================] - 2s 5ms/step - loss: 0.1853 - mae: 0.4388 - val_loss: 0.1821 - val_mae: 0.4393
Epoch 4/10
413/413 [==============================] - 2s 5ms/step - loss: 0.1839 - mae: 0.4365 - val_loss: 0.1786 - val_mae: 0.4356
Epoch 5/10
413/413 [==============================] - 2s 5ms/step - loss: 0.1829 - mae: 0.4359 - val_loss: 0.1821 - val_mae: 0.4370
Epoch 6/10
413/413 [==============================] - 2s 4ms/step - loss: 0.1829 - mae: 0.4354 - val_loss: 0.1777 - val_mae: 0.4303
Epoch 7/10
413/413 [==============================] - 2s 4ms/step - loss: 0.1813 - mae: 0.4333 - val_loss: 0.1806 - val_mae: 0.4322
Epoch 8/10
413/413 [==============================] - 2s 4ms/step - loss: 0.

In [ ]:
model.save("my_model_with_custom_loss_and_threshold.h5")

In [ ]:
model = keras.models.load_model("my_model_with_custom_loss_and_threshold.h5",
                                custom_objects={"huber_fn": create_huber(2.0)})

In [ ]:
model.fit(X_train_scaled, y_train, epochs=2, validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
413/413 [==============================] - 1s 2ms/step - loss: 0.1789 - mae: 0.4283 - val_loss: 0.1731 - val_mae: 0.4254
Epoch 2/2
413/413 [==============================] - 1s 2ms/step - loss: 0.1783 - mae: 0.4281 - val_loss: 0.1891 - val_mae: 0.4343


In [ ]:
class HuberLoss(keras.losses.Loss):
  def __init__(self, threshold=1.0, **kwargs):
    super().__init__(**kwargs)
    self.threshold = threshold
  def call(self, y_true, y_pred):
    error = tf.abs(y_true - y_pred)
    small_error = error < self.threshold
    squared_loss = tf.square(error) / 2
    linear_loss = self.threshold * (error - self.threshold / 2)
    return tf.where(small_error, squared_loss, linear_loss)
  def get_config(self):
    base_config = super().get_config()
    return {**base_config, "threshold": self.threshold}

In [ ]:
custom_model = keras.models.Sequential([
                                        keras.layers.Dense(30, activation='selu', kernel_initializer='lecun_normal', input_shape=X_train.shape[1:]),
                                        keras.layers.Dense(1)
])

In [ ]:
custom_model.compile(loss=HuberLoss(1.5), optimizer="nadam", metrics=['mae'])

In [ ]:
history = custom_model.fit(X_train_scaled, y_train, epochs=10, validation_data=(X_valid_scaled, y_valid))

Epoch 1/10
413/413 [==============================] - 2s 2ms/step - loss: 0.7031 - mae: 0.9188 - val_loss: 0.3246 - val_mae: 0.5787
Epoch 2/10
413/413 [==============================] - 1s 2ms/step - loss: 0.2380 - mae: 0.5149 - val_loss: 0.2495 - val_mae: 0.5158
Epoch 3/10
413/413 [==============================] - 1s 2ms/step - loss: 0.2198 - mae: 0.4947 - val_loss: 0.2111 - val_mae: 0.4834
Epoch 4/10
413/413 [==============================] - 1s 2ms/step - loss: 0.2114 - mae: 0.4852 - val_loss: 0.2131 - val_mae: 0.4754
Epoch 5/10
413/413 [==============================] - 1s 2ms/step - loss: 0.2062 - mae: 0.4772 - val_loss: 0.1959 - val_mae: 0.4624
Epoch 6/10
413/413 [==============================] - 1s 2ms/step - loss: 0.2016 - mae: 0.4716 - val_loss: 0.1990 - val_mae: 0.4632
Epoch 7/10
413/413 [==============================] - 1s 2ms/step - loss: 0.1987 - mae: 0.4668 - val_loss: 0.1892 - val_mae: 0.4543
Epoch 8/10
413/413 [==============================] - 1s 2ms/step - loss: 0.

In [ ]:
custom_model.save("my_model_with_custom_loss_class.h5")

In [ ]:
custom_model = keras.models.load_model("my_model_with_custom_loss_class.h5",
                                       custom_objects={"HuberLoss": HuberLoss})
custom_model.fit(X_train_scaled, y_train, epochs=5, validation_data=(X_valid_scaled, y_valid))

Epoch 1/5
413/413 [==============================] - 2s 2ms/step - loss: 0.1890 - mae: 0.4526 - val_loss: 0.1806 - val_mae: 0.4390
Epoch 2/5
413/413 [==============================] - 1s 2ms/step - loss: 0.1860 - mae: 0.4480 - val_loss: 0.1929 - val_mae: 0.4481
Epoch 3/5
413/413 [==============================] - 1s 2ms/step - loss: 0.1836 - mae: 0.4439 - val_loss: 0.1811 - val_mae: 0.4412
Epoch 4/5
413/413 [==============================] - 1s 2ms/step - loss: 0.1824 - mae: 0.4426 - val_loss: 0.1948 - val_mae: 0.4530
Epoch 5/5
413/413 [==============================] - 1s 2ms/step - loss: 0.1811 - mae: 0.4399 - val_loss: 0.1793 - val_mae: 0.4356


In [ ]:
custom_model.loss.threshold

1.5

In [ ]:
def my_softplus(z):
  return tf.math.log(tf.exp(z) + 1)
def my_glorot_initializer(shape, dtype=tf.float32):
  std = tf.sqrt(2/(shape[0] + shape[1]))
  return tf.random.normal(shape, stddev=std, dtype=dtype)
def my_l1_regularizer(weights):
  return 0.01 * tf.reduce_sum(tf.abs(weights))
def my_positive_weights(weights):
  greater_than_zero = weights > 0
  return tf.where(greater_than_zero, weights, tf.zeros_like(weights))

In [ ]:
layer = keras.layers.Dense(1, activation=my_softplus, kernel_initializer=my_glorot_initializer, kernel_regularizer=my_l1_regularizer, kernel_constraint=my_positive_weights)

In [ ]:
very_custom_model = keras.models.Sequential([
                                             keras.layers.Dense(30, activation='selu', kernel_initializer='lecun_normal', input_shape=X_train.shape[1:]),
                                             layer 
])

In [ ]:
# np.random.seed(42)
# tf.random.set_seed(42)
very_custom_model.compile(loss='mse', optimizer='nadam', metrics=['mae'])
very_custom_model.fit(X_train_scaled, y_train, epochs=5, validation_data=(X_valid_scaled, y_valid))

Epoch 1/5
413/413 [==============================] - 2s 3ms/step - loss: 1.5189 - mae: 0.8728 - val_loss: inf - val_mae: inf
Epoch 2/5
413/413 [==============================] - 1s 2ms/step - loss: 0.6169 - mae: 0.5236 - val_loss: inf - val_mae: inf
Epoch 3/5
413/413 [==============================] - 1s 2ms/step - loss: 0.5328 - mae: 0.4911 - val_loss: inf - val_mae: inf
Epoch 4/5
413/413 [==============================] - 1s 2ms/step - loss: 0.4977 - mae: 0.4793 - val_loss: 2.3700 - val_mae: 0.4974
Epoch 5/5
413/413 [==============================] - 1s 2ms/step - loss: 0.4853 - mae: 0.4763 - val_loss: 1.9556 - val_mae: 0.4901


In [ ]:
very_custom_model.save("my_very_custom_model.h5")

In [ ]:
very_custom_model = keras.models.load_model("my_very_custom_model.h5",
                                            custom_objects={
                                                "my_softplus": my_softplus,
                                                "my_l1_regularizer": my_l1_regularizer,
                                                "my_glorot_initializer": my_glorot_initializer,
                                                "my_positive_weights": my_positive_weights
                                            })

In [ ]:
class MyL1Regularizer(keras.regularizers.Regularizer):
  def __init__(self, factor):
    self.factor = factor
  def __call__(self, weights):
    return self.factor * tf.reduce_sum(tf.abs(weights))
  def get_config(self):
    return {"factor": self.factor}

In [ ]:
layer_with_custom_class = keras.layers.Dense(1, activation=my_softplus, kernel_initializer=my_glorot_initializer, kernel_regularizer=MyL1Regularizer(0.01))

In [ ]:
precision = keras.metrics.Precision()
precision([0, 1, 1, 1, 0, 1, 0, 1], [1, 1, 0, 1, 0, 1, 0, 1])

<tf.Tensor: shape=(), dtype=float32, numpy=0.8>

In [ ]:
precision([0, 1, 0, 0, 1, 0, 1, 1], [1, 0, 1, 1, 0, 0, 0, 0])

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [ ]:
precision.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [ ]:
precision.variables

[<tf.Variable 'true_positives:0' shape=(1,) dtype=float32, numpy=array([4.], dtype=float32)>,
 <tf.Variable 'false_positives:0' shape=(1,) dtype=float32, numpy=array([4.], dtype=float32)>]

In [ ]:
precision.reset_states()

In [ ]:
class HuberMetric(keras.metrics.Metric):
  def __init__(self, threshold=1.0, **kwargs):
    super().__init__(**kwargs)
    self.threshold = threshold
    self.huber_fn = create_huber(2.0)
    self.total = self.add_weight("total", initializer="zeros")
    self.count = self.add_weight("count", initializer="zeros")
  def update_state(self, y_true, y_pred, sample_weight=None):
    metric = self.huber_fn(y_true, y_pred)
    self.total.assign_add(tf.reduce_sum(metric))
    self.count.assign_add(tf.cast(tf.size(y_true), tf.float32))
  def result(self):
    return self.total / self.count
  def get_config(self):
    base_config = super().get_config()
    return {**base_config, "threshold": self.threshold}

In [ ]:
metric = HuberMetric(2.)
metric(tf.constant([[2.]]), tf.constant([[10.]]))

<tf.Tensor: shape=(), dtype=float32, numpy=14.0>

In [ ]:
metric(tf.constant([[0.], [5.]]), tf.constant([[1.], [9.25]]))

metric.result()

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [ ]:
class HuberMetric(keras.metrics.Mean):
  def __init__(self, threshold=1.0, name="HuberMetric", dtype=None):
    super().__init__(name=name, dtype=dtype)
    self.threshold = threshold
    self.huber_fn = create_huber(threshold)
  def update_state(self, y_true, y_pred, sample_weight=None):
    metric = self.huber_fn(y_true, y_pred)
    super(HuberMetric, self).update_state()
  def get_config(self):
    base_config = super().get_config()
    return {**base_config, "threshold": threshold}

In [ ]:
exponential_layer = keras.layers.Lambda(lambda x: tf.exp(x))

In [ ]:
exponential_layer(tf.constant([-1., 0., 1.]))

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.36787945, 1.        , 2.7182817 ], dtype=float32)>

In [ ]:
class MyDense(keras.layers.Layer):
  def __init__(self, units, activation=None, **kwargs):
    super().__init__(**kwargs)
    self.units = units
    self.activation = keras.activations.get(activation)
  def build(self, batch_input_shape):
    self.kernel = self.add_weight(name="kernel", shape=[batch_input_shape[-1], self.units], initializer='glorot_normal')
    self.bias = self.add_weight(name="bias", shape=[self.units], initializer="zeros")
    super().build(batch_input_shape)
  def call(self, X):
    return self.activation(X @ self.kernel + self.bias)
  def compute_output_shape(self, batch_input_shape):
    return tf.Tensorshape(batch_input_shape.as_list()[:-1] + [self.inputs])
  def get_config(self):
    base_config = super().get_config()
    return {**base_config, "units": self.units, "activation": keras.activations.serialize(self.activation)}

In [ ]:
class ResidualBlock(keras.layers.Layer):
  def __init__(self, n_layers, n_neurons, ** kwargs):
    super().__init__(**kwargs)
    self.hidden = [keras.layers.Dense(n_neurons, activation='elu', kernel_initializer='he_normal') for _ in range(n_layers)]
  def call(self, inputs):
    Z = inputs
    for layer in self.hidden:
      Z = layer(Z)
    return Z + inputs

In [ ]:
class ResidualRegressor(keras.models.Model):
  def __init__(self, output_dim, **kwargs):
    super().__init__(**kwargs)
    self.hidden1 = keras.layers.Dense(30, activation='elu', kernel_initializer='he_normal')
    self.block1 = ResidualBlock(2, 30)
    self.block2 = ResidualBlock(2, 30)
    self.out = keras.layers.Dense(output_dim)
  def call(self, inputs):
    Z = self.hidden1(inputs)
    for _ in range(1+3):
      Z = self.block1(Z)
    Z = self.block2(Z)
    return self.out(Z)

In [ ]:
model = ResidualRegressor(1)
model.compile(loss="mse", optimizer="nadam")
history = model.fit(X_train_scaled, y_train, epochs=5, validation_data=(X_valid_scaled, y_valid))
score = model.evaluate(X_test_scaled, y_test)

Epoch 1/5
413/413 [==============================] - 3s 3ms/step - loss: 5.6647 - val_loss: 1.0497
Epoch 2/5
413/413 [==============================] - 1s 3ms/step - loss: 1.7639 - val_loss: 42.3638
Epoch 3/5
413/413 [==============================] - 1s 3ms/step - loss: 0.7850 - val_loss: 1.9676
Epoch 4/5
413/413 [==============================] - 1s 3ms/step - loss: 0.6631 - val_loss: 1.5164
Epoch 5/5
129/129 [==============================] - 0s 2ms/step - loss: 20.9993


In [ ]:
class Reconstructingregressor(keras.models.Model):
  def __init__(self, output_dim, **kwargs):
    super().__init__(**kwargs)
    self.hidden = [keras.layers.Dense(30, activation="selu", kernel_initializer="lecun_normal") for _ in range(5)]
    self.out = keras.layers.Dense(output_dim)
    self.reconstruction_mean = keras.metrics.Mean(name="reconstruction_error")
  def build(self, batch_input_shape):
    n_inputs = batch_input_shape[-1]
    self.reconstruct = keras.layers.Dense(n_inputs)
    # super().build(batch_input_shape)
  def call(self, inputs, training=None):
    Z = inputs
    for layer in self.hidden:
      Z = layer(Z)
    reconstruction = self.reconstruct(Z)
    reconstruction_loss = tf.reduce_mean(tf.square(reconstruction - inputs))
    self.add_loss(0.05 * reconstruction_loss)
    if training:
      result = self.reconstruction_mean(reconstruction_loss)
      self.add_metric(result)
    return self.out(Z)


In [ ]:
my_custom_model = Reconstructingregressor(1)
my_custom_model.compile(loss="mse", optimizer="nadam")
my_custom_model.fit(X_train_scaled, y_train, epochs=10)

Epoch 1/10
413/413 [==============================] - 2s 2ms/step - loss: 0.6216 - reconstruction_error: 0.7297
Epoch 2/10
413/413 [==============================] - 1s 2ms/step - loss: 0.3994 - reconstruction_error: 0.3466
Epoch 3/10
413/413 [==============================] - 1s 2ms/step - loss: 0.3643 - reconstruction_error: 0.2682
Epoch 4/10
413/413 [==============================] - 1s 2ms/step - loss: 0.3545 - reconstruction_error: 0.2352
Epoch 5/10
413/413 [==============================] - 1s 2ms/step - loss: 0.3376 - reconstruction_error: 0.2101
Epoch 6/10
413/413 [==============================] - 1s 2ms/step - loss: 0.3263 - reconstruction_error: 0.1869
Epoch 7/10
413/413 [==============================] - 1s 2ms/step - loss: 0.3177 - reconstruction_error: 0.1602
Epoch 8/10
413/413 [==============================] - 1s 2ms/step - loss: 0.3130 - reconstruction_error: 0.1453
Epoch 9/10
413/413 [==============================] - 1s 2ms/step - loss: 0.3164 - reconstruction_error:

In [ ]:
def f(w1, w2):
  return 3 * w1 ** 2 + 2 * w1 * w2

w1, w2 = tf.Variable(5.), tf.Variable(3.)
with tf.GradientTape() as tape:
  z = f(w1, w2)
gradients = tape.gradient(z, [w1, w2]) 

In [ ]:
gradients

[<tf.Tensor: shape=(), dtype=float32, numpy=36.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=10.0>]

In [ ]:
c1, c2 = tf.constant(5.), tf.constant(3.)
with tf.GradientTape() as tape:
  tape.watch(c1)
  tape.watch(c2)
  z = f(c1, c2)
gradients = tape.gradient(z, [c1, c2])
gradients

[<tf.Tensor: shape=(), dtype=float32, numpy=36.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=10.0>]

In [ ]:
with tf.GradientTape(persistent=True) as hessian_tape:
  with tf.GradientTape() as jacobian_tape:
    z = f(w1, w2)
  jacobians = jacobian_tape.gradient(z, [w1, w2])
hessians = [hessian_tape.gradient(jacobian, [w1, w2]) for jacobian in jacobians]
del hessian_tape
hessians

[[<tf.Tensor: shape=(), dtype=float32, numpy=6.0>,
  <tf.Tensor: shape=(), dtype=float32, numpy=2.0>],
 [<tf.Tensor: shape=(), dtype=float32, numpy=2.0>, None]]

In [ ]:
def f_(w1, w2):
  return 3 * w1 ** 2 + tf.stop_gradient(2 * w1 * w2)

with tf.GradientTape() as tape:
  z = f_(w1, w2)

gradients = tape.gradient(z, [w1, w2])

In [ ]:
gradients

[<tf.Tensor: shape=(), dtype=float32, numpy=30.0>, None]

In [ ]:
x = tf.Variable(100.)
with tf.GradientTape() as tape:
  z = my_softplus(x)
gradients = tape.gradient(z, [x])
gradients

[<tf.Tensor: shape=(), dtype=float32, numpy=nan>]

In [ ]:
def cube(x):
  return x ** 3

tf_cube = tf.function(cube)

In [ ]:
tf_cube(2)